In [89]:
import pandas as pd

df = pd.read_csv("sms+spam+collection/SMSSpamCollection", sep="\t", header=None, names=["label", "message"])
df

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [90]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [91]:
#Converting all the messages into lower case
df.message=df.message.str.lower()
df.head(10)

  label                                            message
0   ham  go until jurong point, crazy.. available only ...
1   ham                      ok lar... joking wif u oni...
2  spam  free entry in 2 a wkly comp to win fa cup fina...
3   ham  u dun say so early hor... u c already then say...
4   ham  nah i don't think he goes to usf, he lives aro...
5  spam  freemsg hey there darling it's been 3 week's n...
6   ham  even my brother is not like to speak with me. ...
7   ham  as per your request 'melle melle (oru minnamin...
8  spam  winner!! as a valued network customer you have...
9  spam  had your mobile 11 months or more? u r entitle...

In [92]:
#Tokenization
import nltk
from nltk.tokenize import word_tokenize
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\krish\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [93]:
df["message"]=df["message"].fillna('').apply(word_tokenize)
df.head()

  label                                            message
0   ham  [go, until, jurong, point, ,, crazy, .., avail...
1   ham           [ok, lar, ..., joking, wif, u, oni, ...]
2  spam  [free, entry, in, 2, a, wkly, comp, to, win, f...
3   ham  [u, dun, say, so, early, hor, ..., u, c, alrea...
4   ham  [nah, i, do, n't, think, he, goes, to, usf, ,,...

In [94]:
df.message = df.message.apply(lambda x : [word for word in x if word.isalpha()])
df.head(10)

  label                                            message
0   ham  [go, until, jurong, point, crazy, available, o...
1   ham                     [ok, lar, joking, wif, u, oni]
2  spam  [free, entry, in, a, wkly, comp, to, win, fa, ...
3   ham  [u, dun, say, so, early, hor, u, c, already, t...
4   ham  [nah, i, do, think, he, goes, to, usf, he, liv...
5  spam  [freemsg, hey, there, darling, it, been, week,...
6   ham  [even, my, brother, is, not, like, to, speak, ...
7   ham  [as, per, your, request, melle, oru, minnaminu...
8  spam  [winner, as, a, valued, network, customer, you...
9  spam  [had, your, mobile, months, or, more, u, r, en...

In [95]:
#Removing all stopwords
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words=set(stopwords.words('english'))
df.message = df.message.apply(lambda x: [word for word in x if not word in stop_words])
df.head(10)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\krish\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

  label                                            message
0   ham  [go, jurong, point, crazy, available, bugis, n...
1   ham                     [ok, lar, joking, wif, u, oni]
2  spam  [free, entry, wkly, comp, win, fa, cup, final,...
3   ham      [u, dun, say, early, hor, u, c, already, say]
4   ham     [nah, think, goes, usf, lives, around, though]
5  spam  [freemsg, hey, darling, week, word, back, like...
6   ham  [even, brother, like, speak, treat, like, aids...
7   ham  [per, request, melle, oru, minnaminunginte, nu...
8  spam  [winner, valued, network, customer, selected, ...
9  spam  [mobile, months, u, r, entitled, update, lates...

In [96]:
#Lemmatization
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()
df.message = df.message.apply(lambda x: [lemmatizer.lemmatize(word) for word in x])
df.head(10)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\krish\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

  label                                            message
0   ham  [go, jurong, point, crazy, available, bugis, n...
1   ham                     [ok, lar, joking, wif, u, oni]
2  spam  [free, entry, wkly, comp, win, fa, cup, final,...
3   ham      [u, dun, say, early, hor, u, c, already, say]
4   ham        [nah, think, go, usf, life, around, though]
5  spam  [freemsg, hey, darling, week, word, back, like...
6   ham  [even, brother, like, speak, treat, like, aid,...
7   ham  [per, request, melle, oru, minnaminunginte, nu...
8  spam  [winner, valued, network, customer, selected, ...
9  spam  [mobile, month, u, r, entitled, update, latest...

In [97]:
#Convert all the token into sentences format
df.message = df.message.apply(lambda x : ''.join(x))
df.head(10)

  label                                            message
0   ham  gojurongpointcrazyavailablebugisngreatworldlae...
1   ham                                 oklarjokingwifuoni
2  spam  freeentrywklycompwinfacupfinaltktsmaytextfarec...
3   ham                        udunsayearlyhorucalreadysay
4   ham                      nahthinkgousflifearoundthough
5  spam  freemsgheydarlingweekwordbacklikefunstilltbokx...
6   ham             evenbrotherlikespeaktreatlikeaidpatent
7   ham  perrequestmelleoruminnaminungintenurunguvettam...
8  spam  winnervaluednetworkcustomerselectedreceiveapri...
9  spam  mobilemonthurentitledupdatelatestcolourmobilec...

In [98]:
#Apply TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
x = tfidf.fit_transform(df["message"]).toarray()

In [99]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, df["label"], test_size=0.2)

In [100]:
#Build MLP model
import tensorflow as tf 
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [101]:
model = keras.Sequential([
    keras.layers.Dense(128, activation='relu', input_shape=(xtrain.shape[1],)),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

c:\Users\krish\tf_env\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [102]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
ytrain = le.fit_transform(ytrain)  # "ham"→0, "spam"→1
ytest = le.transform(ytest)

In [103]:
# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(xtrain, ytrain, epochs=20, validation_data=(xtest,ytest), batch_size=128)

Epoch 1/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8658 - loss: 0.5104 - val_accuracy: 0.8664 - val_loss: 0.3967
Epoch 2/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8658 - loss: 0.3453 - val_accuracy: 0.8664 - val_loss: 0.3714
Epoch 3/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8658 - loss: 0.2557 - val_accuracy: 0.8664 - val_loss: 0.3482
Epoch 4/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8788 - loss: 0.1321 - val_accuracy: 0.9094 - val_loss: 0.3308
Epoch 5/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9998 - loss: 0.0834 - val_accuracy: 0.9094 - val_loss: 0.3419
Epoch 6/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9998 - loss: 0.0438 - val_accuracy: 0.9094 - val_loss: 0.3164
Epoch 7/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9998 - loss: 0.0071 - val_accuracy: 0.9085 - val_loss: 0.3236
Epoch 8/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9998 - loss: 0.0024 - val_accuracy: 0.9094 - val_loss: 0.3252
Epoch 9/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9998 - loss: 0.0018 - val_accuracy: 0.9094 - val_loss: 0.3275
Epoch 10/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9998 - loss: 0.0017 - val_accuracy: 0.9094 - val_loss: 0.3353
Epoch 11/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9998 - loss: 0.0015 - val_accuracy: 0.9067 - val_loss: 0.3288
Epoch 12/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9998 - loss: 0.0012 - val_accuracy: 0.8798 - val_loss: 0.3560
Epoch 13/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9998 - loss: 0.0012 - val_accuracy: 0.9067 - val_loss: 0.3305
Epoch 14/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9998 - loss: 0.0012 - val_accuracy: 0.8987 - val_loss: 0.3361
Epoch 15/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9998 - loss: 0.0011 - val_accuracy: 0.8843 - val_loss: 0.3527
Epoch 16/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9998 - loss: 0.0013 - val_accuracy: 0.9013 - val_loss: 0.3339
Epoch 17/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9998 - loss: 9.8643e-04 - val_accuracy: 0.9094 - val_loss: 0.3678
Epoch 18/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9998 - loss: 0.0011 - val_accuracy: 0.8798 - val_loss: 0.3556
Epoch 19/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9998 - loss: 0.0011 - val_accuracy: 0.9094 - val_loss: 0.3597
Epoch 20/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9998 - loss: 0.0013 - val_accuracy: 0.9094 - val_loss: 0.3615

In [104]:
loss,acc=model.evaluate(xtest,ytest)

35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9094 - loss: 0.3615

In [105]:
acc

0.9094170331954956

In [106]:
model.save("spam_model.keras")

In [107]:
import tf2onnx
import tensorflow as tf
import onnx

model = tf.keras.models.load_model("spam_model.keras")

@tf.function(input_signature=[tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype, name="input")])
def model_fn(x):
    return model(x)

onnx_model, _ = tf2onnx.convert.from_function(
    model_fn,
    input_signature=[tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype, name="input")],
    opset=13
)

onnx.save(onnx_model, "spam_model.onnx")
print("Done ✅")

Done ✅